# Zu beachten: "databases" ist ein Postgresql cluster, welches die Datenbanken "simi" und "postgres" umfasst:
# - "simi": Von der cuba-applikation "simi" genutzte und gemanagte metadatenbank.
# - "postgres": Zieldatenbank für den Schemareader. Ist "Geo-Enabled" und enthält Beispieldatensätze.
version: "3.7"
services:
  simi:
    image: sogis/simi:1.1.58
    environment:
      - CUBA_DATASOURCE_USERNAME=postgres
      - CUBA_DATASOURCE_PASSWORD=postgres
      - CUBA_DATASOURCE_JDBCURL=jdbc:postgresql://localhost:5432/simi?currentSchema=simi
      - CUBA_WEB_LDAP_ENABLED=true
      - CUBA_WEB_LDAP_URLS=ldap://ldap.forumsys.com
      - CUBA_WEB_LDAP_BASE=ou=scientists,dc=example,dc=com
      - CUBA_WEB_LDAP_USER=cn=read-only-admin,dc=example,dc=com
      - CUBA_WEB_LDAP_PASSWORD=password
      - CUBA_WEB_LDAP_USERLOGINFIELD=uid
      - CUBA_WEB_REQUIREPASSWORDFORNEWUSERS=false
      - CUBA_WEB_STANDARDAUTHENTICATIONUSERS=admin
      - CUBA_WEB_PRODUCTIONMODE=true
      - SIMI_CONFIG_STOPONINCOMPLETE=false
      - SIMI_GITSEARCH_URL=https://api.github.com/search/code
      - SIMI_GITSEARCH_REPOS=sogis/gretljobs|oereb/jobs
      - SIMI_PUBLISHJOB_BASEURL=fuu
      - SIMI_PUBLISHJOB_POLLTIMEOUT=5
      - SIMI_PUBLISHJOB_SECTOKEN=secret
      - SIMI_SCHEMAREADER_URL=http://localhost:8081
    ports:
      - "8080:8080"
    network_mode: "host"

